get:
  summary: OpenAPI definition of the service.
  description:
    Endpoint used to retrieve the OpenAPI yaml specification of the service.
  tags:
    - base
  responses:
    '200':
      description: Retrieved the OpenAPI successfully.
      headers:
        X-API-Version:
          $ref: '../components/base.yaml#/components/headers/X-Api-Version'
      content:
        text/vnd.yaml:
          schema:
            $ref: '../components/base.yaml#/components/schemas/EnvelopeOpenapi'
          examples:
            simplified:
              $ref: '../components/base.yaml#/components/examples/EnvelopeOpenapi'
    '500':
      description: Unexpected server error.
      headers:
        X-API-Version:
          $ref: '../components/base.yaml#/components/headers/X-Api-Version'
      content:
        application/json:
          schema:
            $ref: '../components/base.yaml#/components/schemas/EnvelopeNoData'
          examples:
            generic:
              value:
                status:
                  success: false
                  errors:
                    - code: s2.e3.c0
                      message: Human-readable message
